### ISSUE TITLE
Dynamically set `workerData`

### ISSUE THREAD

**Issue by robertsteilberg** [breejs/bree#10]
This is more of a question and not an issue--not sure where might be the best place to post. I can configure a worker with a `workerData` hash so that the scheduled job can have access to some seed data when it runs. However, is there a way to dynamically set this `workerData` hash on each run? Say I have a job that runs every 5 minutes, and every time it runs, I want to repopulate `workerData` with some data from another class in my project fetched via a getter, for example. Is that possible?

**Comment by niftylettuce** [comment]
You could just modify the job data, it's exposed.

```
bree.config.jobs[3].workerData = {
  // some new data here
};
```

Then next time it runs it would use that.
