### ISSUE TITLE
how to deploy Bree in kubernetes container platform

### ISSUE THREAD

**Issue by BrijJhala** [breejs/bree#100]
what i understand from nod-schedule home page that bree can be used for muti node cluster environment. now my question is how to I do scheduling to kubernetes container platform using bree. For example : I would like to schedule few jobs on pod1 and few other jobs on pod2. i.e. i can scale horizontally. appreciate your help !

**Comment by bkstorm** [comment]
I have the question. What happens if two pods schedule the same job from database? Or I have to handle it by myself.

**Comment by niftylettuce** [comment]
Handle the queue yourself, we have an example in the README.  This is simply a job scheduler, you can add the glue on top with your database.
