### ISSUE TITLE
Publish type definitions

### ISSUE THREAD

**Issue by axelrindle** [breejs/bree#101]
I use VSCode for JavaScript development and currently it's spitting out the following error when constructing a new `Bree` instance:

```js
new Bree({
    // ...
});

// => error TS2350: Only a void function can be called with the 'new' keyword.
```

As I haven't truly tested `Bree` yet, I don't know if this has an impact on the functions of `Bree`, but it's kinda annoying for development. Publishing either the contents of the `src/` directory or separate type definitions would probably be a huge improvement.

If that is somehow relevant, some version strings:

- VSCode: `1.55.0`
- Node.js: `v14.15.5`
- OS: Ubuntu `20.04.2` LTS (Kernel `x64 5.4.0-62-generic #70-Ubuntu`)

**Comment by Iceapinan** [comment]
+1

**Comment by shadowgate15** [comment]
This issue is likely due to VSCode using `tsserver` which is based on typescript which this project will not be supporting. Please see previous issues on typescript, for the reasonings behind this.

I do believe if you add to your `jsconfig.js` file the following it will remove this error:
```
"compilerOptions": {
  "checkJs": true
}
```
