### ISSUE TITLE
Worker for job exited with code 1

### ISSUE THREAD

**Issue by petersondrew** [breejs/bree#105]
I'm trying to trace down a message showing up in my logs that doesn't appear to correlate with any error messages: `Worker for job "JobName" exited with code 1`. The job metadata oddly includes `threadId: -1`, so that further leads me to believe it's not associated with a job originating from any errors.

Looking through the source code, it seems fairly straightforward that this message is logged when the `exit` event is raised. Without a corresponding error I'm unsure what would trigger it however. My only hunch is that perhaps it has something to do with using cancellation? I noticed that the listener for `exit` is not removed on cancellation as it is on `done`.

Really, I'm mostly looking for assurance that it's innocuous, and I'd also be happy to submit a PR to address it if it's not some kind of error on my part. I began work on a repro but I'm unsure exactly how to repro it reliably.

**Comment by shadowgate15** [comment]
If you could reproduce that would be great!

If you run `bree.stop()`, it will terminate the worker. When a worker is terminated it will return a code of 1, please see this [documentation](https://nodejs.org/api/worker_threads.html#worker_threads_event_exit). This might be what is happening, but would be great to see a reproduction of the error to confirm.

**Comment by petersondrew** [comment]
I think the documentation you referenced is precisely what's happening - something is calling `exit` on the worker thread, though I'm not using `bree.stop()`. I am however setting `closeWorkerAfterMs` to 120 seconds, which I'm guessing is the reason I'm seeing this message!

Do you know what the intended use case for `closeWorkerAfterMs` is? I may be using it incorrectly.

**Comment by shadowgate15** [comment]
The purpose of `closeWorkerAfterMs` is to allow you to set a timeout on the individual worker. Workers are created each time a job is run.

For example, if I had the following job `./jobs/cormac.js`:
```javascript
setTimeout(() => {
  process.exit(2);
}, 180000) // timeout set for 3 minutes
```
with the following `bree.config`:
```javascript
{
  jobs: [
    {
      name: "worker-1",
      path: "./jobs/cormac.js",
      interval: "2m", // set to run every 2 minutes
      closeWorkerAfterMs: 60000, // set to 1 minute
    },
    {
      name: "worker-2",
      path: "./jobs/cormac.js",
      interval: "2m", // set to run every 2 minutes
    }
  ]
}
```

`worker-1` would terminate the worker before the next interval. `worker-2` would throw an error when the next interval comes up because the worker would still be running.
