### ISSUE TITLE
Repeat job in x time

### ISSUE THREAD

**Issue by Nisgrak** [breejs/bree#112]
Hi!

I would like have a 'repeat' param to when the job finish it relaunch in the given time.

Example TestJob with repeat at 2000ms:

1.  Start the program
2. Bree launch the TestJob
3. TestJob finish
4. Wait the 2000ms
5. Bree launch again TestJob
6. TestJob finish
7. Wait the 2000ms
8. Bree launch again TestJob
and go on.....

**Comment by niftylettuce** [comment]
See `interval` option in README https://github.com/breejs/bree#job-options

**Comment by niftylettuce** [comment]
Oh, I see, from when it finishes.

**Comment by niftylettuce** [comment]
Here you go:

```js
const bree = new Bree({
  jobs: [
    { name: 'test', timeout: false }
  ]
});

function startOnFinish() {
  bree.run('test');
  bree.workers.test.on('exit', () => setTimeout(startOnFinish, 2000));
}

startOnFinish()
```

**Comment by niftylettuce** [comment]
Note I updated it to use `once` instead of `on`.

**Comment by Nisgrak** [comment]
Nice! Thanks you 😄 

PD: Anyway an option in the job object would be nice, all available out-of-the-box are awesome.
