### ISSUE TITLE
Auto worker threads creation

### ISSUE THREAD

**Issue by bipinstha7** [breejs/bree#114]
Hi, I'm trying to run a long-running (approx: 10 -15 min) cron job with Bree. While running the jobs it blocks the main event loop. The app doesn't return the response to the health check route (which is outside Bree). The Bree package is supposed to create and run the jobs in worker threads right? or did I miss something? Please help me.
#### If Bree is supposed to create a worker thread why it blocks the event loop? I'm running `for loop` of  `i < 1e20` (to block and test). I created the custom worker thread (without Bree) and it's working(doesn't block the event loop i.e health check route returns the response)

**Comment by shadowgate15** [comment]
how are you determine that health check route returns the response?

If it is doing so via `stdout` inside of the worker, it won't send it until the worker quits...there are several issues on this as well as documentation within the docs.

**Comment by bipinstha7** [comment]
@shadowgate15 , The health check route is outside of the worker thread, just a simple express route. While using the Nodejs worker-thread module, the health check route returns the response (when worker-thread running and doing computation) but while using Bree it blocks the main thread (health check stuck). 
How do I run Bree so that the main thread doesn't block? If blocking the main thread is what Bree does then what is the use of it? I might have missed something. Could you please point me out?

**Comment by shadowgate15** [comment]
hmmm that is strange. it shouldn't be blocking the main thread. what is the DEBUG info showing?

**Comment by bipinstha7** [comment]
@shadowgate15 Thank you for your response.
I haven't done debugging, it just blocks the event loop. AND, I haven't used `graceful`, is it necessary? Doc says it's optional.

**Comment by shadowgate15** [comment]
you shouldn't have to use graceful... although we do suggest it. if you mocked up a test repro or gist, I can take a look at it. I do suggest checking the debugging output though.

**Comment by bipinstha7** [comment]
@shadowgate15 , I've created a gist. Please have a look [here](https://gist.github.com/bipinstha7/3e39d4028a0975314129907fff185d71)

**Comment by shadowgate15** [comment]
So although the job itself is running in it's own thread every time `postMessage` is called it blocks the main loop to output the message. If you add something like `i % 10000 === 0` to that if statement (effectively making it only output a message every 10000 iterations), it will then allow the GET request to be processed.

If you look at the real world examples, you will notice that bree is run in it's own process not in the same process as the web app which will mitigate this problem as well.
