### ISSUE TITLE
Silent fail when job interval is neither a later nor human-interval format

### ISSUE THREAD

**Issue by FlyingPumba** [breejs/bree#115]
I saw in the documentation that `"on the first day of the month"` works as an interval and assumed that `"on the fifth day of the month"` would work as well. However, it is not a valid string neither for the later nor human-interval libraries. Sadly, the human-interval library returns `0`, instead of `NaN` for this particular string, so no error is thrown and the job does not work (it never fires).

Lucky for me, the string `on the 5th day of the month` does work as intended (it is a valid later format), but perhaps it would be good to change the Bree code so that it interprets a `0` from human-interval library as an error.
I believe the change needed is this line: https://github.com/breejs/bree/blob/master/src/job-utils.js#L56

**Comment by shadowgate15** [comment]
@FlyingPumba if you want to make a PR we will gladly review it!
