### ISSUE TITLE
extend configuration to hook worker messages

### ISSUE THREAD

**Issue by delcon** [breejs/bree#120]
I find logging and monitoring subpar because of the fixed message templates.
How about extending the configuration  object to be able to hook into messages from worker threads?

config:
```javascript
{
    name : "foo",
    interval: "2min",
    onMessage: (message) => {  },
    onExit: (info) => { },
    .....
}
```

If you are interested I could write a pull request.

Also I would like to be able to mute the logger with `logger: null`

**Comment by shadowgate15** [comment]
There is already this [option](https://github.com/breejs/bree#custom-errormessage-handling).
