### ISSUE TITLE
How can send a message from Main thread to a Bree job

### ISSUE THREAD

**Issue by ilovebioz** [breejs/bree#122]
I want to stop a job when it is running. To do this, I think I need to send a message from the main thread to the job.
But I don't know how to do it. Pls help.

**Comment by shadowgate15** [comment]
You can do this by calling `bree.stop('jobName')`

this will then send a message called 'cancelled' to worker. See [this](https://github.com/breejs/bree#cancellation-retries-stalled-jobs-and-graceful-reloading)
