### ISSUE TITLE
Emit and listen to custom events?

### ISSUE THREAD

**Issue by DnOberon** [breejs/bree#124]
Forgive me if this isn't the place to post this, or if I missed something so obvious in the readme.

Is there any way for us to listen to custom events emitted from the bree workers on the main thread?

**Comment by shadowgate15** [comment]
So sort of. Check out the [Custom error/message events](https://github.com/breejs/bree#custom-errormessage-handling). This would let you create something similar to that using Node's communication systems. If you are looking for something more than that. We would gladly look at a pull request.
