### ISSUE TITLE
Some question about using this library

### ISSUE THREAD

**Issue by JoHuang** [breejs/bree#13]
Hi, this library seems quite attractive to me. I would like to ask some questions.
Assuming I have a microservice node.js app to queue jobs from http request. input looks like:
```
{
     "id": "1234",
     "fireAt" : "15xxxxxxxxxx",
     "name" : "job_name" // refer to job_name.js
     "data" : {"someJSONdata": "data" }
}
```
And I have 3 instances (A,B,C) of this service in a cluster which also contains Redis and MongoDB.
1. If instance A queued a job, but before it being fired, instance A somehow crashed. How to recover the job?
    I read that you suggest to query databases in worker.js to prevent duplicated jobs. But how about recovering?
2. I saw you have an example of worker which connect to MongoDB inside it. Is it a good practice to connect to database every time the job being fired? Is there a worker thread pools to reuse threads (and maybe database connections)?
3. In my use case,  jobs could be canceled frequently. Maybe only 20% jobs fired. How to implement this case? The `id` in input fields is used to overwrite the current queued job. For example:
    a) Got `id:"1234"` job with 2s delay to be fired. Enqueue it.
    b) 1s later, got `id:"1234"` job with 10s delay to be fired. Cancel the job in a), enqueue the new job.
    c) 10s later, fire `id:"1234"` job queued in b)

Thanks for you patience.

**Comment by niftylettuce** [comment]
You should verbosely write out all of this logic.  I think that if you are encountering problems where only 20% of jobs fire, or you are running into MongoDB connection issues, or if the jobs crashed ... then you are having bad code practices, or architecting your project incorrectly.

See https://github.com/breejs/express-example for an Express example of using a persistent storage (example uses file storage, but you could use persistent MongoDB).  If you want more rich examples of Bree in-action with concurrency and MongoDB persistence, see the "jobs" folder of https://github.com/forwardemail/forwardemail.net at <https://github.com/forwardemail/forwardemail.net/tree/master/jobs>.
