### ISSUE TITLE
[feat] Better Typescript support / documentation

### ISSUE THREAD

**Issue by dan003400** [breejs/bree#133]
The docs / examples on Typescript are very poor and hard to understand, would be nice if the examples were not half baked and had a full example on setup.

```
  ...(CRON_MODE === 'ts'
      ? {
            path: typescript_worker,
            worker: {
                workerData: {
                    __filename: path.join(paths.jobs, `${jobPath}.ts`)
                }
            }
        }
      : {
            path: path.join(paths.jobs, `${jobPath}.js`)
        })
```

This is in particular makes no sense, what is `paths`, where is `jobPath` coming from, are you actually writing this ternary for every job?

**Comment by nikosgpet** [comment]
Just came up with this issue myself. Better typescript support would be greatly appreciated indeed.

**Comment by dan003400** [comment]
I have found that its "working" without doing any of the documented path hacks.

**Comment by shadowgate15** [comment]
I do plan on building a typescript plugin for bree that will allow you to run .ts files, as well as, improving the declaration file and moving it to be shipped with the package.

**Comment by shadowgate15** [comment]
the path hacks are primarily for use when compiling with something that changes the file system structure.

**Comment by shadowgate15** [comment]
Please see [@breejs/ts-worker](https://github.com/breejs/ts-worker)! Send feature requests and bug fixes there! I will work on getting type declarations in package soon.
