### ISSUE TITLE
fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by danwetherald** [breejs/bree#134]
When running bree script from a docker image we are seeing this error immediately once starting.

`fatal: not a git repository (or any of the parent directories): .git`

**Comment by shadowgate15** [comment]
Could you share your Dockerfile?

**Comment by dan003400** [comment]
```
FROM node:latest

WORKDIR /app

COPY package.json .

RUN yarn install

COPY . .

CMD ["node", "dist/cron.js"]
```
