### ISSUE TITLE
[bug] update typescript bindings to include extend method for plugins 

### ISSUE THREAD

**Issue by paularah** [breejs/bree#138]
The extend method for the Bree class isn't included in the typescript definitions, this prevents extending Bree with plugins like the ts-worker plugin.

**Comment by shadowgate15** [comment]
Will hopefully have a PR for DefinitelyTyped later today!

**Comment by paularah** [comment]
Thank you👍🏿

**Comment by paularah** [comment]
Halo @shadowgate15,  any updates on this?

**Comment by shadowgate15** [comment]
@paularah I'm still waiting on DefinitelyTyped's maintainers to approve our [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57025)

**Comment by shadowgate15** [comment]
if you update to bree@7.1.0 typescript bindings are now bundled with package!
