### ISSUE TITLE
[fix] Typescript type errors in the package

### ISSUE THREAD

**Issue by feralheart** [breejs/bree#146]
#### Describe the bug

 - Node.js version: 16.13
 - Bree.js version: 7.1

#### Actual behavior
I've added this package to my typescript project and upon building I've got these errors:

```
node_modules/bree/types/index.d.ts:3:30 - error TS2307: Cannot find module 'node:events' or its corresponding type declarations.

3 import { EventEmitter } from 'node:events';

node_modules/bree/types/index.d.ts:4:39 - error TS2307: Cannot find module 'node:worker_threads' or its corresponding type declarations.

4 import { WorkerOptions, Worker } from 'node:worker_threads';
```

#### Expected behavior
No type errors inside the package

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Bree.

**Comment by shadowgate15** [comment]
@feralheart Do you have `@types/node` installed as a dev dependency?

**Comment by arimus** [comment]
Looks like this is due to old @types/node definitions being installed in my case. Updated to the 16.x release and that solved this issue for me.
