### ISSUE TITLE
[feat] Option to disable logging

### ISSUE THREAD

**Issue by MA-MacDonald** [breejs/bree#147]
Could you add an option to disable logging? 

I have many jobs running and the logging going to the console is making it hard to read some other outputs I am sending to the console.

**Comment by shadowgate15** [comment]
You can pass a noop logger to Bree in the constructor.

**Comment by MA-MacDonald** [comment]
ok thanks I'll try that.

**Comment by niftylettuce** [comment]
We should add ability to pass false as a Boolean @shadowgate15 which would
in turn make it a noop

**Comment by SpellChucker** [comment]
FYI for anyone wanting to do this, you can provide your logger as follows:
```
const bree = new Bree({
  ...
  logger: { info: () => {}, error: () => {}, warn: () => {} },
  ...
});
```

Not pretty but will do as suggested.

**Comment by niftylettuce** [comment]
You can set `logger: false` in v7.1.2 now, just published to npm 🔥 

https://github.com/breejs/bree/releases/tag/v7.1.2
