### ISSUE TITLE
using bree inside a react remix app?

### ISSUE THREAD

**Issue by movingelectrons** [breejs/bree#150]
how can I do this?  The docs say to add 'type': 'module' to package.lock, but when I do I can no longer start the remix app, yarn run dev fails with a very generic exited with code 1..  removing the type:module from package.lock and it runs again just fine.

**Comment by Spence-S** [comment]
hi @movingelectrons - remix is a full stack react framework that does a lot of magic for you, so it makes stuff hard to understand sometimes when you want something advanced. I don't know much about it, but you just have to ensure that Bree is set up on the server side and that bree is looking for job files in the right location, after everything is bundled by remix. 

You should only use `type: module` if remix tells you to do so, bree can work either way, as long as its the same as remix.

The remix [docs](https://remix.run/docs/en/v1/api/conventions#serverbuilddirectory) here show they do compile and bundle their server code. so you need to be looking at the server bundle and ensure Bree code is there and has all its jobs as files exactly where it expects them. see [usage with bundlers](https://github.com/breejs/bree#typescript-and-usage-with-bundlers)

You may want to open this question in remix to get more clarity on exactly how remix would recommend setting up workers/bree on the server side.

**Comment by shadowgate15** [comment]
I'm considering this closed. If you need more help just let us know!
