### ISSUE TITLE
[discussion] Segmentation Fault Ubuntu X64

### ISSUE THREAD

**Issue by DaRabus** [breejs/bree#157]
Hey Guys, I started to setup my Bee workers to make my tasks in a worker thread externally.

But as soon as my task wants to start a 2nd time it crashes with following issue:

Do I have to close the Threads in another way, or do they get generated wrong? Got the same issue now on my Windows Testing environment, just here it just fails without throwing me an error.

### I am using an express server as a base of instance, could this be root of the issue?

`
![image](https://user-images.githubusercontent.com/44967066/153176706-667627b1-ce92-4bc2-be72-29bb4af51348.png)

![image](https://user-images.githubusercontent.com/44967066/153177546-4dd81274-91d7-44ba-ac3b-5f98dd2ccd91.png)

**Comment by DaRabus** [comment]
> It looks like one job is ending in the same tick as the next one starts. You might try making sure there is at least a space of one tick between ending and starting the next job.

Thanks, so i will give him more time to reallocate the memory, there is no command to set the memory free or so?

**Comment by shadowgate15** [comment]
actually could you run this with NODE_DEBUG=* or NODE_DEBUG=bree* and post the log output. If my previous statement were true, I'm pretty sure you would have seen a log output saying the worker was already running.

**Comment by DaRabus** [comment]
https://pastebin.com/8G3Szf4W

Doesnt really provide me much informations tbh.

On Windows it just crashes without a proper error

**Comment by shadowgate15** [comment]
I would look into lines 334 & 336. I don't think this is being cause by bree. Bree looks to be running correctly. Typically Segmentation faults are caused by attempting to access restricted or illegal parts of memory.
