### ISSUE TITLE
[fix] Jobs starting slowly

### ISSUE THREAD

**Issue by maxpain** [breejs/bree#184]
## Describe the bug

**Node.js version:** 18.4.0

**OS version:** Container-Optimized OS with containerd (cos_containerd)

**Description:** It took ~30 seconds to start a Job

## Actual behavior
The thread/worker goes online fast, but actual code execution starts after ~30 seconds.

<img width="679" alt="image" src="https://user-images.githubusercontent.com/5875582/174624840-d2e297a7-ab51-4cbc-b3ce-3fc14cbc9c2b.png">

## Expected behavior
Code execution to start within a second.

## Code to reproduce
```typescript
/* eslint-disable import/first */
console.log('[start-scheduled-stages] Import modules')

import { startScheduledStages } from '@fastcup/backend-common/tournaments/stages/handle/schedule-stages'
import logger from '@fastcup/backend-common/log'
import { isTournamentAutomationEnabled } from '../utils/index.js'
import { initSentry } from '../utils/sentry.js'

initSentry()

logger.info('[start-scheduled-stages] Start')
if (await isTournamentAutomationEnabled()) {
	await startScheduledStages()
} else {
	logger.warn('Tournament automation is disabled')
}

logger.info('[start-scheduled-stages] done')
```

## Checklist

- [x] I have searched through GitHub issues for similar issues.
- [x] I have completely read through the README and documentation.
- [x] I have tested my code with the latest version of Node.js and this package and confirmed it is still not working.

**Comment by maxpain** [comment]
@shadowgate15 
```typescript
const jobs = [
	{ name: 'sync-tournament-streams', cron: '* * * * *' },
	{ name: 'start-scheduled-matches', cron: '* * * * *' },
	{ name: 'start-scheduled-rounds', cron: '* * * * *' },
	{ name: 'start-scheduled-stages', cron: '* * * * *' },
	{ name: 'start-scheduled-tournaments', cron: '* * * * *' },
	{ name: 'start-scheduled-stage-check-ins', cron: '* * * * *' },
	{ name: 'auto-accept-tournament-matches', cron: '* * * * *' },
	{ name: 'cleanup', cron: '* * * * *' },
	{ name: 'update-streams', cron: '*/5 * * * *' },
	{ name: 'update-top-users', cron: '*/10 * * * *' },
	{ name: 'update-friends-online', cron: '* * * * *' },
	{ name: 'update-statistic-counters', cron: '* * * * *' },
	{ name: 'statistic-minutely', cron: '* * * * *' },
	{ name: 'statistic-hourly', cron: '0 * * * *' },
	{ name: 'statistic-daily', cron: '0 0 * * *' },
	{ name: 'statistic-monthly', cron: '0 0 1 * *' },
	{ name: 'statistic-yearly', cron: '0 0 1 1 *' },
	{ name: 'gamemoney-checkouts', cron: '* * * * *' },
	{ name: 'pay-ladder-prizes', cron: '* * * * *' },
	{ name: 'sync-workshop-maps', cron: '* * * * *' },
]

const bree = new Bree({
	root: path.join(path.dirname(fileURLToPath(import.meta.url)), 'jobs'),
	jobs,
	logger: breeLogger,
	closeWorkerAfterMs: 10 * 60 * 1000,
	errorHandler(error) {
		logger.error(error)
		sentry.captureException(error)
	},
})

bree.start()
```

**Comment by shadowgate15** [comment]
I wonder if that is due to the number of workers that are being created at one time and causing a delay due to it loading all of those files.

Does it continue to have the delay after the first time the job runs? Also, do all of the jobs have that delay?

**Comment by maxpain** [comment]
> Does it continue to have the delay after the first time the job runs?
Yes, I have consistent from 10 to 30 seconds delay in every launch of every job.

<img width="791" alt="image" src="https://user-images.githubusercontent.com/5875582/174639721-a05f81f0-6f9e-45a5-873e-d07a60d9c434.png">

**Comment by shadowgate15** [comment]
Does your logger use `console`? If it does, there is a known [node issue](https://github.com/breejs/bree#custom-errormessage-handling) with that. Try adding the time stamp in the logger string to determine that. It could potentially be that the awaits are actually taking that long to run and due to the above issue the logs are getting backed up and giving inaccurate time information.

**Comment by maxpain** [comment]
Seems the problem is that I have a lot of jobs, they have a lot of imports and when starting they consume CPU a lot. The code of a job itself doesn't consume the CPU that much, but Node imports do.

![screen](https://user-images.githubusercontent.com/5875582/174918590-a37edc55-4922-48b0-95c8-ef04c172c184.gif)

Should I stop using Bree / worker_threads and run all my jobs in the same process?

**Comment by shadowgate15** [comment]
hmm interesting. One solution could be to use longer running jobs. another solution might be to reduce the size of the imports so they load faster.

**Comment by maxpain** [comment]
I already use ES Modules, IDK how to make my modules load faster. Anyway, we use npm packages, which can be CommonJS modules and destroy performance.

**Comment by maxpain** [comment]
Is there a way to cache imports in worker_threads?
