### ISSUE TITLE
Interval parsing issue

### ISSUE THREAD

**Issue by ChrisEdgington** [breejs/bree#23]
Specifying a job interval of `every 10 seconds` as opposed to `10s` results in the following very confusing error:

```internal/worker.js:200
    this[kPort].postMessage({
                ^

DOMException [DataCloneError]: function(d) {
        return getInstances("next", 1, d, d) !== later.NEVER;
      } could not be cloned.
    at new Worker (internal/worker.js:200:17)
    at Bree.run (/Users/cedgington/repos/personal/temp/express-example/node_modules/bree/index.js:573:28)
```

You can see this by simply using the example project (as I did) and modify only the interval.

**Comment by niftylettuce** [comment]
Almost done with the fix

**Comment by ChrisEdgington** [comment]
LOL - I just was about to post - debugged it to a problem with how you're using later. Guess I'll wait ...

**Comment by niftylettuce** [comment]
v1.1.26 has been released to npm

try it out and it should work OK for you @ChrisEdgington - let me know otherwise

I published deprecation notice as well for all versions prior

**Comment by niftylettuce** [comment]
https://github.com/breejs/bree/releases/tag/v1.1.26

**Comment by ChrisEdgington** [comment]
The parsing and initial run now works - but then Bree exits, which is different behavior than the other syntax.

const taskman = new bree({
    jobs: [
        { name: 'Worker 1', path: worker_1, interval: 'every 5 seconds' },
        { name: 'Worker 2', path: worker_2, interval: 'every 10 seconds' },
    ]
})

These jobs run once then Bree exits.

-Chris

**Comment by niftylettuce** [comment]
Can you share a reproducible test case or repository I can run?

**Comment by ChrisEdgington** [comment]
const Bree = require('bree');

const bree = new Bree({
  jobs: [
    {
      name: 'Exiter',
      path: worker,
      interval: 'every 10 seconds'
    }
  ]
});

function worker() {
  console.log('I am working ...')
}

bree.start();

**Comment by niftylettuce** [comment]
looking into this, thanks

**Comment by niftylettuce** [comment]
I see what's wrong, it's a similar issue where it's not checking for `isValid`

**Comment by niftylettuce** [comment]
Got the fix, one sec

**Comment by niftylettuce** [comment]
The core bug all along with this whole issue was this line:

```js
      const schedule = later.schedule(later.parse.text(value));
      if (schedule.isValid()) return schedule;
```

Instead of returning `schedule`, we needed to return `later.parse.text(value)` instead.

**Comment by niftylettuce** [comment]
v1.1.27 released, try it out and let me know if this works for you @ChrisEdgington 

https://github.com/breejs/bree/releases/tag/v1.1.27

I also published deprecation notice for all versions prior.

**Comment by ChrisEdgington** [comment]
LOL - yes, I had already fixed the problem there - but I just changed it to return schedule.next(1). I was surprised by your initial fix and decided, “Wow, I must not understand what is going on."

**Comment by niftylettuce** [comment]
🤦 sorry hahahaha

**Comment by ChrisEdgington** [comment]
1.1.27 appears to be working properly - thanks for the fix.

**Comment by niftylettuce** [comment]
Great to hear, thank you @ChrisEdgington for confirmation.  If you need anything else or have questions let me know.
