### ISSUE TITLE
Using typescript files

### ISSUE THREAD

**Issue by ChrisEdgington** [breejs/bree#24]
Just a tip for anyone wanting to use typescript files instead of javascript. Make sure your project is already setup for ts-node.

Setup the job like this:

```
{ 
    name: 'Typescript Worker', 
    path: typescript_worker, 
    interval: 'every 10 seconds', 
    worker: { workerData: { __filename: './src/job_specific_filename_worker.ts' } } 
}
```

With the `typescript_worker` function like this:

```
function typescript_worker() {
    const path = require('path')
    require('ts-node').register()
    const workerData = require('worker_threads').workerData
    require(path.resolve(__dirname, workerData.__filename))
}
```

**Comment by niftylettuce** [comment]
If you would like to submit a PR to update the docs with this, and also perhaps the mention of using DefinitelyTyped for TS bindings, I'm open to it

**Comment by ChrisEdgington** [comment]
Ahh, thanks for the nudge, I’m an old-school dev getting used to GitHub / open-source. I’ll review the guidelines and see if I can get a proper PR submitted :)

**Comment by niftylettuce** [comment]
No guidelines really, I would gladly help make cleanups

**Comment by niftylettuce** [comment]
Old-school devs are the best kind of devs to have around 🤘
