### ISSUE TITLE
[feat] browser support

### ISSUE THREAD

**Issue by niftylettuce** [breejs/bree#27]
Right now browser support is unstable due to these issues:

- [ ] <https://github.com/chjj/bthreads/issues/5>
- [ ] <https://github.com/chjj/bthreads/issues/4>
- [ ] <https://github.com/chjj/bthreads/issues/6>

I previously had modified `index.html` with a basic example such as this:

```html
  <script src="https://unpkg.com/bree">
  <script>
    (function() {
      function hello() {
        console.log('hello');
        postMessage('done');
      }

      var bree = new Bree({
        jobs: [
          {
            name: 'hello',
            path: hello,
            interval: '5s',
          }
        ]
      });

      bree.start();
    })();
  </script>
```

However since `postMessage` is not working, I have it commented out right now.

Note that I do expose `threads` from `bthreads` as `Bree.threads`, therefore one could write a browser test (e.g. with puppeteer that uses `Bree.threads.backend === 'web_worker'` and `Bree.threads.browser === true` to test that the proper backends load.

**Comment by hyusetiawan** [comment]
can this be worked around if it's running on electron?

**Comment by shadowgate15** [comment]
I'm closing this issue since bree no longer supports the browser.

**Comment by c0bra** [comment]
> I'm closing this issue since bree no longer supports the browser.

If that's the case, can you remove _Works in the browser_ from `index.html`?
