### ISSUE TITLE
support for priority based jobs 

### ISSUE THREAD

**Issue by stavalfi** [breejs/bree#35]
thanks for this great work. 

what is the status of this feature? is this planned? in progress?

**Comment by shadowgate15** [comment]
What do you mean by priority based jobs?

**Comment by stavalfi** [comment]
more info: https://docs.bullmq.io/guide/jobs/proritized

(it is natively supported by bull and bullmq)

**Comment by niftylettuce** [comment]
Priority should be handled with custom logic on an individual job by job basis

You could make a job that polls every 5s for jobs, and sorts them by a field you create called "priority", and if you sort desc to asc, then 10... 5... 1.. etc would be your results.  Assuming you use priority of 10 as the highest priority, you could then use something like `p-map` to handle concurrency and only run X number of jobs pulled at once.

**Comment by stavalfi** [comment]
Thanks for the fast repley :) 

I'm not sure how your suggestion solves:

1. speed - we have realtime application. pulling every 5 second is not acceptable =\
2. error handeling - if an instance pulls multiple jobs, what happen if the instance crush without processing all of them?
3. multi-instances support - how do you propose to use your solution in multi-instances enviroment? if each instance pulls multiple job, sort them and manage them, it can't be scaled. 

it feels like too much of the job-managment will be on the application. 


maybe I misunderstood you.
