### ISSUE TITLE
worker with same interval as closeWorkerAfterMs permanently terminated

### ISSUE THREAD

**Issue by robertsteilberg** [breejs/bree#38]
If any worker has an interval equal to `closeWorkerAfterMs` set on the Bree object, they will be terminated after one run and fail to restart.

I've been meaning to do a better job of demonstrating this behavior or even fixing the bug but I am too busy at the moment.

**Comment by shadowgate15** [comment]
Correct me if I'm wrong @niftylettuce. That would be the intended effect of the `closeWorkerAfterMs` option. 

If you are trying to set a limit on how long the worker is processing for, that should be taken care of by the worker.

**Comment by robertsteilberg** [comment]
I want my worker to run every 5000 ms so I set an `interval` of `5s`. If the worker itself takes more than 5000 ms to run, then yes, it should be closed. However, this has not been the case--it is being terminated regardless of how long it takes, and it is only termined in this way when `interval === closeWorkerAfterMs`.

**Comment by robertsteilberg** [comment]
Ha, I'm an idiot, I misread the doc. Closing. Thanks for the correction @shadowgate15
