### ISSUE TITLE
same job file different para meters

### ISSUE THREAD

**Issue by marcpar** [breejs/bree#39]
hello is is possbile to have 

`
jobs:[{
name: "jobA",
interval: 15,
   workerData:{
          test: "taska"
   },
name: "jobA",
interval: 15,
   workerData:{
          test: "taskb"
   },
}]
`

**Comment by niftylettuce** [comment]
yeah, just do `name: "jobA"` and `name: "jobB"` but also pass a path of `path: "/path/to/same-job.js"`
