### ISSUE TITLE
How to use with multiple instances?

### ISSUE THREAD

**Issue by danielopitz** [breejs/bree#4]
Hi, Bree looks very promising. Thanks for the hard work!

I have hacked together a mail queue which checks for unsent mails every x seconds and sends them out. My problem is: I'm running more than one instance of the application and use Postgres locks to make sure no mail is sent twice (only one instance has access to the queue at the same time). 

Is there any way to solve this with Bree? Or would I still need to use locking?

**Comment by niftylettuce** [comment]
Keep it simple and just use locking
