### ISSUE TITLE
Interval at specific time and cron not working

### ISSUE THREAD

**Issue by Dream4ever** [breejs/bree#40]
Environment:
- Windows Server 2012
- Node.js 12.18.4
- Task is managed by PM2

I'm using bree now, however, only `interval: '30s'` works. Neither `interval: 'at 09:28 am'` nor `cron: '18 9 * * *'` works. I'm using the following code:

```js
const Bree = require('bree');

const bree = new Bree({
  jobs: [
    {
      name: 'daily-report',
      interval: '30s', // works
      // interval: 'at 09:28 am', // not working
      // cron: '18 9 * * *', // not working
    },
  ]
});

bree.start();
```

**Comment by shadowgate15** [comment]
I just tested this and it worked. If you are still having trouble, could you upload a debug log.

**Comment by niftylettuce** [comment]
Thanks @shadowgate15 - closing until @Dream4ever provides a reproducible repository or gist/code.
