### ISSUE TITLE
Extend Bree from EventEmitter and emit events when workers start, etc

### ISSUE THREAD

**Issue by tiaod** [breejs/bree#5]
I want to call the method in the main thread in the worker,  and I found [comlink](https://github.com/GoogleChromeLabs/comlink) will be a good choice, but I don't know how to use it with bree. 
I need to call `Comlink.wrap(worker)` whenever bree starts a new worker, but there is no hooks or event to listen to. 🤔

**Comment by niftylettuce** [comment]
You should just be able to postMessage and listen for messages between Bree and the workers, no?

**Comment by tiaod** [comment]
You can get workers through bree.workers[name], but how do you know when the workers will start?

**Comment by niftylettuce** [comment]
Can you share code snippet of what you're trying to accomplish?  This seems like unnecessary complexity.

**Comment by tiaod** [comment]
```js
// jobs/test.js
const { parentPort } = require('worker_threads');

function wait(t){
  return new Promise(resolve=>setTimeout(resolve, t))
}

async function main(){
  parentPort.postMessage('I\'m alive!');
  await wait(10000)
  console.log('done!')
}
main()
```
```js
const Bree = require('bree')
const bree = new Bree({
  jobs:[
    {
      name:'test',
      // interval: '10s'
    }
  ]
})

bree.run('test')

// You can get workers through bree.workers[name]
bree.workers['test'].on('message', (event) => {
  console.log(`Received message from worker: ${event}`)
});
```
However, when you schedule a job:
```js
const Bree = require('bree')
const bree = new Bree({
  jobs:[
    {
      name:'test',
      interval: '10s'
    }
  ]
})

bree.start()

bree.workers['test'] // Undefinded, because the worker not started running
```
How do you know when the workers will start?

**Comment by niftylettuce** [comment]
I'm going to re-open this as we could simply extend Bree from EventEmitter class from Node and then emit certain events when workers start, close, etc, that you could listen on.

**Comment by niftylettuce** [comment]
v1.1.17 released to npm with this added:

https://github.com/breejs/bree/releases/tag/v1.1.17

See the README for more information and examples on how to listen for when they start:

https://github.com/breejs/bree#listening-for-events

Let us know if you need anything else.

**Comment by tiaod** [comment]
Here is an example used with comlink.
```js
// main.js
const Bree = require('bree')
const Comlink = require('comlink')
const nodeEndpoint  = require('comlink/dist/umd/node-adapter')
const bree = new Bree({
  jobs:[
    {
      name:'test',
      interval: '15s'
    }
  ]
})
const api = {
  doMath() {
    return 4;
  },
};
bree.on('worker created', name=>{
  Comlink.expose(api, nodeEndpoint(bree.workers[name]))
})
bree.start()
```

```
// jobs/test.js
```
