### ISSUE TITLE
Using functions for jobs

### ISSUE THREAD

**Issue by webbels** [breejs/bree#58]
Hello, 

I have red a part of your document indicated: 

> It is highly recommended to use files instead of functions. However, sometimes it is necessary to use functions.

And we really need to use functions now. 
Once we initiate a function to be executed along with cron: 

<img width="571" alt="Screen Shot 2020-11-27 at 10 46 32 PM" src="https://user-images.githubusercontent.com/18644029/100460599-6cccf880-3102-11eb-8ff3-205432cffc4a.png">

We get this error:
<img width="788" alt="Screen Shot 2020-11-27 at 10 45 38 PM" src="https://user-images.githubusercontent.com/18644029/100460536-4e66fd00-3102-11eb-8116-066690bcaa5a.png">

Would you please assist us with this?

**Comment by naz** [comment]
@webbels have you tried specifying `root: false` in the options you pass into Bree constructor? The error seems like it's trying to look for a job module in the filesystem instead of executing the function you provided in `path`.

**Comment by webbels** [comment]
That worked. Thank you!
Below updated Bree init for future reference: 

<img width="664" alt="Screen Shot 2020-12-01 at 5 51 03 PM" src="https://user-images.githubusercontent.com/18644029/100724417-d0ef0580-33fd-11eb-97b0-7074f18d0196.png">


I also recommend updating the document with a full example. 

Thank you!

**Comment by webbels** [comment]
@naz , Cron should still work when using functions, right?

**Comment by naz** [comment]
@webbels I think so, yes.

**Comment by naz** [comment]
@niftylettuce we can close this issue  :wink:

**Comment by webbels** [comment]
@naz , Sorry for keeping you here, but seems cron is not running with functions. below is the Object I'm mapping for jobs:

<img width="549" alt="Screen Shot 2020-12-01 at 7 02 00 PM" src="https://user-images.githubusercontent.com/18644029/100732480-b883e880-3407-11eb-8bf9-53c6ca78f815.png">

Coming from https://www.npmjs.com/package/ngx-cron-editor

I'm expecting function to be executed every minute.

**Comment by webbels** [comment]
It was an issue with said library. We can close this.
Thanks!
