### ISSUE TITLE
[bug] bthreads require is needed for proper error handling in worker scripts

### ISSUE THREAD

**Issue by naz** [breejs/bree#63]
## Problem
When the worker script is defined without any dependencies it does not emit an 'error' event described in [node documentation](https://nodejs.org/dist/latest-v14.x/docs/api/worker_threads.html#worker_threads_event_error).

### Reproduction steps
Register a job in with bree that points to following script:
```js
// contents of uncaught-exception.js file
(async () => {
    throw new Error('catch me if you can');
})();
```
when the job executes observe the log:
1. There is an uncaught error in the log `(node:37046) UnhandledPromiseRejectionWarning: Error: catch me if you can`
2. Bree logs the worker exit as if it was successful: `Worker for job "uncaught-exception" exited with code 0`

The expected behavior would be no unhandled exception in the log and exit code 1.

### Quick fix
To fix the situation load `bthreads` module with the job script, e.g.:
```js
// contents of uncaught-exception-corrected.js file
require('bthreads');

(async () => {
    throw new Error('catch me if you can');
})();
```

### Solution
I think it's worth documenting need to include `bthreads` in each job script and advice against using native `worker_threads` module as that causes unexpected behavior with unhandled exceptions within job scripts.

**Comment by igorovic** [comment]
Thanks you!
Your quick fix was very helpful.

**Comment by shadowgate15** [comment]
this is no longer an issue since we have dropped bthreads.
