### ISSUE TITLE
[dicsussion] merges vs rebases 

### ISSUE THREAD

**Issue by naz** [breejs/bree#67]
Is there a preference on how PRs/changes from branches are merged into master? 

I have slight preference towards keeping the master as clean as possible so would prefer clean rebase or squash+rebase combination. Can check an example project history using this pattern in Ghost - https://github.com/TryGhost/Ghost/commits/master.

 Don't mind keeping the current pattern as well. Just wanted to have this written down somewhere for clarity :)

**Comment by naz** [comment]
@niftylettuce @shadowgate15 do you have any particular opinions on this topic?

**Comment by niftylettuce** [comment]
I have no opinion really, as long as git log is not too crazy, as long as stuff gets shipped is my mentality

**Comment by naz** [comment]
Awesome. I'll stick to the habit of rebasing changes to keep the log clean. I'm on the same page regarding optimization towards shipping speed :+1:
