### ISSUE TITLE
[question] Is this lib support timezone

### ISSUE THREAD

**Issue by ikhsanalatsary** [breejs/bree#72]
just curious. I think, it's good to have.

**Comment by naz** [comment]
Hi @ikhsanalatsary . Could you please expand on what exactly your usecase is and ideally provide some examples of the changes you'd like to see. Thanks!

**Comment by t0lik** [comment]
In the current project I have to start all cron jobs at a certain time indicated for the CET timezone. I'd prefer not to indicate all times in GMT. Now I'm using [cron](https://www.npmjs.com/package/cron) package, it has ability to indicate either a timezone or an UTC offset. Your package is great but this timezone support lack stopping me from trying to use it.

**Comment by niftylettuce** [comment]
Cron is native to the filesystem's timezone (this is handled outside of Node by things like tzdata on Linux machines).  So you cannot use `* * * * *` to set a recurring cron schedule based off a time, however you could combine both `date` and `interval`, and have the `date` be a JavaScript Date object, and therefore the interval would run after the date (timeout).

**Comment by t0lik** [comment]
Can you please show an example for `45 22 * * *` keeping in mind that this time is in CET timezone and we are executing a scheduler's job on a computer with GMT timezone.

**Comment by niftylettuce** [comment]
There are examples in the README as to how to construct `date` and
`interval`.  You can use `ms` to combine days, minutes, hours and use that
value as `interval`, and construct a `date` object with
`dayjs-with-plugins` package (or just `dayjs`).

**Comment by andrewchen5678** [comment]
> In the current project I have to start all cron jobs at a certain time indicated for the CET timezone. I'd prefer not to indicate all times in GMT. Now I'm using [cron](https://www.npmjs.com/package/cron) package, it has ability to indicate either a timezone or an UTC offset. Your package is great but this timezone support lack stopping me from trying to use it.

Same here, lack of built in timezone support is preventing me from using bree, I also ended up resorting to use https://www.npmjs.com/package/cron instead.

**Comment by niftylettuce** [comment]
The latest version has built-in local timezone support already.

**Comment by niftylettuce** [comment]
As of v5.0.0 see https://github.com/breejs/bree/releases/tag/v5.0.0 and https://github.com/breejs/bree/commit/5d56016f2ae4e9d047ad91edcb6e2c9e8c2d0930

**Comment by andrewchen5678** [comment]
But it doesn’t allow me to specify a timezone that want to use for cron. While all other libraries allow me to customize the timezone to use for the job.

**Comment by t0lik** [comment]
@niftylettuce Do you have any plans to add a custom timezone support?

**Comment by knicola** [comment]
@andrewchen5678 and @t0lik there's no reason for bree to handle timezone conversions. It is beyond its scope. You should either change the server's timezone or use a 3rd party library (such as moment, dayjs or luxon) to handle the conversion for you. Here's an example of how you would use [`luxon`](https://github.com/moment/luxon):
```js
// ...
const { DateTime } = require('luxon')

const bree = new Bree({
  jobs: [
    {
      name: 'simpleJob',
      date: DateTime
        .fromISO('2025-01-27T09:30:00', { zone: 'America/New_York' })
        .toLocal()
        .toJSDate(),
    }
  ]
})
// ...
```

**Comment by t0lik** [comment]
@knicola The fact is I don't need a certain date to launch scheduled jobs. I need to indicate a time part only like I mentioned above `45 22 * * *` which means `Launch every day at 22:45`.

**Comment by knicola** [comment]
@t0lik you can also format the output of luxon, and other libraries, to match your needs.
https://moment.github.io/luxon/docs/manual/formatting.html#toformat
```js
{
  cron: DateTime
    .fromISO('2025-01-27T09:30:00', { zone: 'America/New_York' })
    .toLocal()
    .toFormat('mm HH * * *')
}
```

**Comment by t0lik** [comment]
Sorry, I meant I already have several cron settings and all schedules indicated as a cron-compatible strings like `45 22 * * *`. So to use them I just need to pass them to a scheduler, indicate a timezone in options and that's all.

**Comment by knicola** [comment]
@t0lik I see. I've put something together to do timezone conversions for cron expressions. It is by no means optimized or even bug free, but hopefully it'll get you closer to what you are looking for:

```js
// known issues:
// - will ignore steps (anything after a `/`)
// - does not work with expressions that include seconds and/or years
// - will not advance days of week or month
const { DateTime } = require('luxon')

function cronTz(cronString, fromTz, toTz) {
    const hours = cronString
        .split(' ')[1] // get cron-hours
        .split(',') // get time ranges
        .map(range => {
            return range
                .split('/')[0] // ignore steps
                .split('-') // get hours
                .map(hour => { // tz conversion for each hour
                    return DateTime
                        .now()
                        .startOf('day')
                        .plus({ hour: hour })
                        .setZone(fromTz, { keepLocalTime: true })
                        .setZone(toTz) // or .toLocal() ?
                        .hour
                })
        })
        .reduce((res, pair) => { // format time ranges
            const h1 = pair[0]
            const h2 = pair[1]

            if (pair.length === 1) {
                return res.concat(h1)
            }

            if (h1 > h2) {
                return res.concat([
                    h1 === 23 ? h1 : `${h1}-23`,
                    h2 === 0 ? h2 : `0-${h2}`,
                ])
            }

            return res.concat(pair.join('-'))
        }, [])
        .join(',') // format cron-hour string

    const cronParts = cronString.split(' ')
    cronParts[1] = hours
    return cronParts.join(' ')
}

cronTz('45 22 * * *', 'America/New_York', 'Europe/Paris') //=> "45 4 * * *"
cronTz('* 16,19-23,1-6,8 * * 1-5', 'America/New_York', 'Europe/Paris') //=> "* 22,1-5,7-12,14 * * 1-5"
```

A much better solution would perhaps be to do the timezone conversion on the next scheduled run in bree. That would cover cron, text and dates too.

**Comment by Asheboy** [comment]
I have a similar requirement to @t0lik. I have tasks that need to run at the same time daily for a specific location. For locations which change time due to daylight savings, this can be problematic. With other packages (Agenda, Node-Cron), you are able to pass a timezone (e.g. `Europe/London` when defining a task which handles this problems. Does bree support this, or have guidance on how to achieve this? Thank you!

**Comment by niftylettuce** [comment]
Would love a PR and tests for this.

**Comment by niftylettuce** [comment]
Another approach you could do is to set a `date` property on the job option, and an `interval` of `24h` or something.  That way it runs at a given date/timezone and on your specified interval.

**Comment by knicola** [comment]
I poked around under the hood and from what I can tell the best way to go about it is to first patch `@breejs/later`'s [.setTimeout()](https://github.com/breejs/later/blob/master/src/index.js#L1188) (either directly or in bree), since it's the one creating the intervals, and then add bree instance and job options for timezones (ie. `fromTz` and `toTz`). There's a package that adds timezone conversion to `later` called [`later-timezone`](https://github.com/firstandthird/later-timezone/blob/master/index.js) which could probably be used as a reference.

That's as far as I got. If I find more time I might attempt a PR but no promises.

**Comment by andrwo** [comment]
I'm evaluating which job schedulers to adopt now, and I just like to chime in that being able to handle timezones (not strictly on server timezone) like how `node-cron` does it (passing timezone as a parameter into the construction) would be really good.

**Comment by shadowgate15** [comment]
@andrwo If you want to create a pull request, we would be happy to review it.

**Comment by niftylettuce** [comment]
@knicola would love a PR!

**Comment by knicola** [comment]
@niftylettuce still needs tests but I believe this should do it: https://github.com/knicola/bree/commit/a4d3b7c989c2fb3472c2a5c275a5ff38bd8e0819

**Comment by shadowgate15** [comment]
I'm closing seeing as the current version of `bree` and `@breejs/later` can handle timezone.

**Comment by t0lik** [comment]
Please add examples with timezone in README
