### ISSUE TITLE
[question] Is using bree with a singleton a correct approach ?

### ISSUE THREAD

**Issue by UserSina** [breejs/bree#73]
### Context: 
I'm creating a bree scheduler in the main **app.j**s of an **express** app.
I have two scheduler routes, one to stop the scheduler and another to start it.

I ultimately want to initially create and start the  scheduler in **app.js**, then I want to freely stop and start it in **schedulerRoutes.js**

### Questions:
- Is this approach safe and scalable for production ?
- If not what are the alternatives ?

### Code: 
> Scheduler.js

```JAVASCRIPT
class Scheduler {
  constructor() {
    this.bree = null;
  }

  // - Create a new scheduler and assign it to this.bree
  createScheduler = async () => {
    ...Generate myJobs

    this.bree = new Bree({
      root: false,
      jobs: myJobs,
      errorHandler: (error, workerMetaData) => {
        console.log(
          `There was an error while running a worker: ${workerMetaData.name}`
        );
      },
    });
  };

  // - Can be called from routes
  startScheduler = () => {
    if (this.bree) this.bree.start();
  };

  // - Can be called from routes
  stopScheduler = () => {
    if (this.bree) this.bree.stop();
  };

  // - Add a worker

  // - Remove a worker
}

module.exports = new Scheduler();
```

> SchedulerRoutes.js

```JAVASCRIPT
var express = require('express');
var router = express.Router();

const Scheduler = require('path/to/Scheduler');
var scheduler = Scheduler;

router.get('/start', scheduler.startScheduler);

router.get('/stop', scheduler.stopScheduler);
```

> app.js

```JAVASCRIPT
const Scheduler = require('path/to/Scheduler');
var scheduler = Scheduler;
var schedulerRouter = require('./routes/schedulerRoutes');

// Start the scheduler after 5 seconds
setTimeout(async () => {
  await scheduler.createScheduler();
  scheduler.startScheduler();
}, 5000);

app.use('/', indexRouter);
app.use('/users', usersRouter);
app.use('/scheduler', schedulerRouter);
```

**Comment by shadowgate15** [comment]
Why would you need to start and stop bree entirely and the app continue to run...instead of just adding and removing individual jobs as necessary?

**Comment by UserSina** [comment]
The app needs to continue to run because it's linked to a front end as well. Moreover, I have a peculiar case where the user gets to decide if all of the jobs are running or not. Is it not recommended to stop and start the bree in this case? 

**Alternative:** I also thought about making `myJobs` an attribute for the class then loop through and stop the corresponding worker names. Is this a better solution than entirely stopping bree ?

**Comment by shadowgate15** [comment]
@UserSina Sorry for the huge delay in getting back to you on this. I would not start and stop bree but either stop that specific job or have the front-end trigger a system to add or remove jobs from bree.

Something to note if you do add a job it will need to be started separately from starting all of bree.

Also, I would have the front-end send a response that contains the job name and stop it via bree instead of iterating through a list, since bree already does this on the backend. Probably not that big a deal on a small scale but is adding extra work to the system.
