### ISSUE TITLE
Interval job runs only once, no recurrence

### ISSUE THREAD

**Issue by adrfantini** [breejs/bree#77]
Hi, sorry if this is probably a really stupid question question.
I am trying to test `bree` from the `Node.js v12.16.1` terminal by running a simple function repeatedly with a given interval, like so:
```
const interval = 'every 5 seconds'
const Bree = require('bree');
const bree = new Bree({
    root: false,
    jobs: [
        {
            name: 'myJob',
            inteval: interval,
            path: function() {
                console.log(new Date())
            }
        },
    ]
})
bree.start()
```
The job does start the first time, with the following output:
```
2021-01-18T15:16:27.252Z
Worker for job "myJob" online undefined
Worker for job "myJob" exited with code 0 undefined
```
But recurrence does not seem to take place. The job is never repeated.
What is going on?

**Comment by niftylettuce** [comment]
Is it because you have a typo of `inteval`?

**Comment by adrfantini** [comment]
:facepalm: 
sorry
