### ISSUE TITLE
bree.start(workerId) should return the created worker

### ISSUE THREAD

**Issue by knownasilya** [breejs/bree#79]
Due to not having access to the original worker I cannot use the `parentPort` to receive messages from the main process, instead I have to do things like: 

```js
bree.add([
  {
    name: 'query-action',
    worker: {
      transferList: [port1],
      workerData: { data, port: port1 },
    },
  },
]);

port2.on('message', (message) => {
  console.log(message);
});

bree.start('query-action');
```

This could be avoided if the worker was returned, then I could listen for events on the worker and send them from the worker using `parentPort`.

**Comment by knownasilya** [comment]
Looks like I found the answer

```js
bree.on('worker created', (name) => {
  console.log('worker created', name);
  console.log(bree.workers[name]);
});
```

**Comment by knownasilya** [comment]
This solves the original question, but would still like to do something like `bree.start('name', { worker: { workerData }})` Because the data changes across each manual run.

**Comment by niftylettuce** [comment]
PR welcome, I think if you pass workerData it should override anything and be used as the workerData object instead (users can manually inherit properties from default config since it's exposed).
