### ISSUE TITLE
how should I handle a cron service in multiple node (MSA)

### ISSUE THREAD

**Issue by oojikoo** [breejs/bree#81]
I currently running 2 nodes for a api service in k8s and I'd like to add cron job to the service. 

but if I do, a cron job will be executed twice (one per node).

of course, I can create a new service for cron which resolves this issue.

is there a job/cron registration management across multiple nodes?

**Comment by shadowgate15** [comment]
If you look at the way bree is used in [lad](https://github.com/ladjs/lad.sh), you will see that we use a separate service. This way all of the jobs are started concurrently, not asynchronously.
