### ISSUE TITLE
Question on intermediate job update (triggered by a user action)

### ISSUE THREAD

**Issue by sehmaschine** [breejs/bree#84]
Sorry if this has been asked before. I've searched the issues but couldn't find an answer.

We currently use bree with cron-triggered jobs and this works very well.
But we also have jobs which are triggered by a user action (clicking a button within an admin UI). For this usecase we need to start a job and then update the UI while the job is running. The job is analyzing ~100.000 documents (which takes quite a while) and we have to update the frontend with some information on how many docs are already processed (the user should see something like a percentage value at least).

What's the best way to achieve this with bree?

Note: We just switch from Python/Celery/RabbitMQ. So in general, I know how this workflow can be implemented. I'm just not sure how it should be done with bree.

**Comment by shadowgate15** [comment]
I could see two options for this. Either option could be triggered by a setInterval or in the iterator the worker is running.

Option 1 (Best): Have the worker update a database field periodically. The frontend can then poll the database.
Option 2: Have the worker send messages back to the parent. This will likely still require a database update. The frontend can then poll the database or other method you use to push the message from the worker to the frontend.
