### ISSUE TITLE
Question: How to use pino transport with bree?

### ISSUE THREAD

**Issue by meotimdihia** [breejs/bree#86]
Hi, I think a lot about this question but still can't solve it.
https://github.com/pinojs/pino/blob/master/docs/transports.md

Currently, I have to use the "child logger" to filter job logging.
https://github.com/pinojs/pino/blob/master/docs/child-loggers.md
But it still not really good.

**Comment by niftylettuce** [comment]
Use CabinJS https://cabinjs.com, it is recommended and pino usage is documented in our README https://github.com/breejs/bree#node and on the CabinJS docs
