### ISSUE TITLE
[feat] Configurable logging formatter

### ISSUE THREAD

**Issue by naz** [breejs/bree#89]
refs https://github.com/TryGhost/Ghost/issues/12496

### Problem

Currently the logger is called with 2 parameters when there's an [incoming message](https://github.com/breejs/bree/blob/abbf0c6b767e579f0a51138589d897237211e102/src/index.js#L301-L304) from the worker without a way to customize logged object format. 

This is fine for the situation when logger is configured to specifically handle this type of format (`(string, object)`). In more complex systems thought, logging is usually very centralized and has an established system-wide format. Bending to the interface of internal logger to the needs of dependent libraries would not make sense in such situations

### Proposed solution

Introduce a custom handler for logger message similar to [errorHandler](https://github.com/breejs/bree/#instance-options) allowing to format the logging message with available information.

**Comment by naz** [comment]
@niftylettuce similarly to `errorHandler` I'll be adding a `workerMessageHandler` which would override logging a message to calling this callback function instead. The naming choice was made because: (1) keeping the `Handler` post-fix convention like with `errorHandler` and (2) it's worker's `message` event which this callback will be hooking into. 

I plan to release this handler as a minor asap as there's a [pressing bug](https://github.com/TryGhost/Ghost/issues/12496#issuecomment-781809619) with file handles leak related to this feature. Having this handler gives a way to process log messages through `parentPort.postMessage()` communication instead of using logger module inside the worker files. Bonus, allows to make jobs even lighter :tada:

**Comment by niftylettuce** [comment]
sounds good - as long as Cabin stays in referenced as a default and the default console is there too that's great

**Comment by naz** [comment]
awesome! all the default stay as is :heavy_plus_sign: the PR is almost on the way, gonna put it out there in a bit
