### ISSUE TITLE
Better directory resolution for workers

### ISSUE THREAD

**Issue by robertsteilberg** [breejs/bree#9]
Hi there. This is a great little scheduling library that is much easier to use out of the box compared to some of the alternatives.

One thing that has been a bit of an itch is directory resolution. For apps like express, I don't want to have all my jobs sitting at `<repo>/jobs` by default; I'd like them to be somewhere in `<repo>/src/jobs` or `<repo>/src/path/to/services/jobs` or something. I can avoid `<repo>/jobs` by setting `root: false` on the instance, but then I need to individually set the full path of each worker in the `jobs` array. I also can't use a relative path like `./jobs/worker` that is `require`-esque, I need to do something like `'${__dirname}/jobs/test.js'`, which is just a bit ugly in my opinion and produces repeated code unless I pull out `'${__dirname}/jobs/'` out into a variable somewhere.

**Comment by niftylettuce** [comment]
Great to hear, thank you for your kind words @robertsteilberg!  That was my goal.

You shouldn't need to individually set the full path, you could just override `root` with the path, e.g. `root: path.join(__dirname, 'src/jobs')`?

**Comment by niftylettuce** [comment]
Let me know if previous comment works for you?

**Comment by robertsteilberg** [comment]
Ah! My mistake. I seemed to have failed to realize that `root` itself could be set to the path. It would still be great if a path could be a relative string, but since this implementation works fine, I will close this issue.
