### ISSUE TITLE
[bug] stray log output needs removed

### ISSUE THREAD

**Issue by niftylettuce** [breejs/bree#90]
https://github.com/breejs/bree/blob/04575da2ac7b0b7864ae53968713372b37ce55f9/src/index.js#L236

cc @naz

**Comment by niftylettuce** [comment]
also @naz I noticed a few typos here https://github.com/TryGhost/Utils/blob/main/packages/job-manager/lib/job-manager.js#L39

**Comment by naz** [comment]
@niftylettuce yupppp :grimacing: fixing this right now!

**Comment by naz** [comment]
stray date logging fixed with 1fbca4c

**Comment by naz** [comment]
will fix up the Ghost spelling separately at some point. my spelling and spellchecking plugins failed to catch those errors, so I better configure them properly to avoid similar fails in the future :sweat_smile:

**Comment by niftylettuce** [comment]
![tumblr_mzxh8wvNkT1ryfbj1o1_640](https://user-images.githubusercontent.com/523141/108672763-3d7f1b00-74a8-11eb-9854-e4e558d60cbb.gif)
