### ISSUE TITLE
Way of knowing how job was started in event listeners?

### ISSUE THREAD

**Issue by nickbarrow** [breejs/bree#91]
We use Bree to schedule jobs and also to run them manually if necessary. Our issue is that we like to log the start and finish times of the job, among other pieces of data. We have the DB insert "started" whenever a worker is created using `bree.on('worker created')`. However, we want a slightly different log when a job is run manually, including things like username of job runner. As you could imagine, this causes the job start to log twice, as bree's 'worker created' event is triggered on manual runs as well. Is there a way to know if a job was triggered manually vs scheduled? Or does anyone have a solution to how I could log on a scheduled job run without using `bree.on('worker created')`? Thanks!

**Comment by shadowgate15** [comment]
You could pass that kind of info in using `workerData` when you create the job.
