### ISSUE TITLE
Seg Fault when a task is run with process.exit(0) and it runs twice 

### ISSUE THREAD

**Issue by admazzola** [breejs/bree#96]
Worker for job "collectTokenParameters" online undefined
PID 28681 received SIGSEGV for address: 0x0
/media/andy/Starflask/dev2/tokenpool/node_modules/segfault-handler/build/Release/segfault-handler.node(+0x3127)[0x7fec6f5b1127]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12890)[0x7fec8816b890]
node(napi_delete_reference+0x28)[0x9d7cf8]
/media/andy/Starflask/dev2/tokenpool/node_modules/secp256k1/prebuilds/linux-x64/node.napi.glibc.node(_ZN14Secp256k1Addon4InitEN4Napi3EnvE+0xe9c)[0x7fec6f9df73c]
/media/andy/Starflask/dev2/tokenpool/node_modules/secp256k1/prebuilds/linux-x64/node.napi.glibc.node(_Z4InitN4Napi3EnvENS_6ObjectE+0x16)[0x7fec6f9d9d56]
/media/andy/Starflask/dev2/tokenpool/node_modules/secp256k1/prebuilds/linux-x64/node.napi.glibc.node(_Z11__napi_InitP10napi_env__P12napi_value__+0x5e)[0x7fec6f9d9e3e]
node(_Z30napi_module_register_by_symbolN2v85LocalINS_6ObjectEEENS0_INS_5ValueEEENS0_INS_7ContextEEEPFP12napi_value__P10napi_env__S8_E+0x20e)[0x9ee05e]
node[0x9efd6c]
node(_ZN4node7binding6DLOpenERKN2v820FunctionCallbackInfoINS1_5ValueEEE+0x222)[0x9ef142]
node[0xc02fc9]
node(_ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE+0xb7)[0xc04db7]
node[0x140a8f9]
Segmentation fault (core dumped)

Node v12

**Comment by shadowgate15** [comment]
We need to see the code to help you with this.

**Comment by rashiq-ddc** [comment]
Any update on this ?

**Comment by shadowgate15** [comment]
I can't update due to us not being given the code for the job.
