### ISSUE TITLE
How can a job stop/remove itself from bree's schedule?

### ISSUE THREAD

**Issue by twhiston** [breejs/bree#97]
Hi, I'm working on an app that does a lot of dynamic recurring job scheduling, I have some conditions upon which the job should be stopped/removed from bree completely (eg the thing it is querying has been deleted or become unavailable). How can I do this from within the worker? I couldn't see any kind of message to pass back to the parent or method by which to obviously do this, but that's probably because I'm new to Bree and nodejs Workers in general! Any help would be appreciated, thanks.

**Comment by shadowgate15** [comment]
you can post a message from the worker of `'done'` to kill the job. 
See [test/jobs/done.js](https://github.com/breejs/bree/blob/6957f90735d0ef5151fcd2eebdab6ec323620c58/test/jobs/done.js)
