### ISSUE TITLE
How to pass arguments (js object) from master process to job sub-process?

### ISSUE THREAD

**Issue by MurzNN** [breejs/bree#98]
I need to pass some objects from main process to job as arguments, that launched from separate js file, but can't find the example how to do this. 

Can you please provide some example, how this feature can be implemented using Bree jobs? Thanks!

**Comment by MurzNN** [comment]
I investigated that we can pass the `argv` options and even JS objects via `workerData`, but both of them isn't support passing functions, so seems they are not suitable solutions.

**Comment by shadowgate15** [comment]
Could you show us an example of your use case?

**Comment by csprocket777** [comment]
Passing functions to worker threads isn't supported. It's not a clonable object. See `workerData`
https://nodejs.org/api/worker_threads.html#worker_threads_new_worker_filename_options

**Comment by niftylettuce** [comment]
You could stringify the function and then eval it on the other side, but that's an anti-pattern
