### ISSUE TITLE
Unable to run MongoDB operations in Jobs 

### ISSUE THREAD

**Issue by rajathongal** [breejs/bree#99]
Getting this message on nodejs server startup
` MongooseError: Operation `Collection.find()` buffering timed out after 10000ms`

**Comment by niftylettuce** [comment]
https://github.com/Automattic/mongoose/issues/9732

**Comment by rajathongal** [comment]
> [Automattic/mongoose#9732](https://github.com/Automattic/mongoose/issues/9732)

Hey Thanks for the reply but the issue didn't resolve with the solution you provided but the real issue was mongoose was trying to create multiple connections and the solution was to create the connection when you want to execute a script and close the connection just after it, refer here []((https://stackoverflow.com/a/52606262/12386847))

**Comment by niftylettuce** [comment]
one sec let me get you an example of something I wrote

**Comment by niftylettuce** [comment]
here's a 80 line code example of connecting to mongoose and disconnecting gracefully too https://github.com/forwardemail/forwardemail.net/blob/master/jobs/account-updates.js

**Comment by rajathongal** [comment]
> here's a 80 line code example of connecting to mongoose and disconnecting gracefully too https://github.com/forwardemail/forwardemail.net/blob/master/jobs/account-updates.js

Thank you this will surely help a lot do check my connection method - 
```
//imports
const mongoose = require("mongoose");

require("dotenv").config();


//temp var init
let connectionString = "";
mongoose.Promise = global.Promise;

//connection logic
if (process.env.NODE_ENV === "production") {
  
    connectionString =  "" ;

  } else if (process.env.NODE_ENV === "development") {

    connectionString = process.env.TEST_MONGODB_URI;

  } else {

    connectionString = "";
}

const connectDB = async (databaseName) => {
    try {
      await mongoose.connect(connectionString, {
        useCreateIndex: true,
        useNewUrlParser: true,
        useFindAndModify: false,
        useUnifiedTopology: true,
        dbName: databaseName,
      });
  
      console.log("MongoDB connected...");
    } catch (err) {
      console.log(err.message);
      process.exit(1);
    }
};

module.exports = connectDB; 
```
